config/routes.rb
Simplesite::Application.routes.draw do
  resources :users, only: [:new, :create, :destroy]

  namespace "admin" do
    get '',to: 'cars#index'
    resources :cars do
      get 'delete_asset' => "cars#delete_asset"
    end
    post 'update_list', to: 'cars#update_list'
    get 'filter', to: 'cars#filter'
    get 'search_by_price', to: 'cars#search_by_price'

    resources :models
    resources :makes
  end

  namespace "front" do
    resources :makes, only: [:index,:show]do
      resources :models, only: [:show,:index]do
        resources :cars, only: [:show,:index] do
        end
      end
    end
  end
  root to: 'index#home'

  resources :sessions, only: [:new, :create, :destroy]

  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy', via: :delete

  get '/signup',  to: 'users#new'

 

  

end

app/models/make.rb
class Make < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  attr_accessible :name,:avatar

  has_many :models, dependent: :destroy
  has_many :cars, dependent: :destroy

  validates :name, presence: true
  validates_uniqueness_of  :name

  default_scope order: 'makes.created_at DESC'

  mount_uploader :avatar, AvatarUploader
end

app/controllers/admin/makes_controller.rb
class Admin::MakesController < Admin::AdminController

  before_filter   :have_a_make, only: [:edit,:show,:update,:destroy]

    def index
      @makes = Make.all
    end

    def new
      @make = Make.new
    end

    def create
      @make = Make.new(params[:make])
      if @make.save
        flash[:success] = "Create make success"
        redirect_to admin_makes_path
      else
        render 'new'
      end
    end

    def show
    end

    def edit
    end

    def update
      if @make.update_attributes(params[:make])
         @make.slug = nil
         @make.save
        redirect_to admin_make_path(@make)
      else
        render 'edit'
      end
    end

    def destroy
      @make.destroy
      flash[:info] = @make.name+" destroyed."
      redirect_to admin_makes_path
    end

    private

    def have_a_make
      unless @make = Make.friendly.find(params[:id])
        not_found
      end
    end
end

app/controllers/front/makes_controller.rb
class Front::MakesController < Front::FrontController
  def index
    render json: Make.all
  end
  def show
    render json: Make.friendly.find(params[:id])
  end
end

app/helpers/admin/makes_helper.rb
module Admin::MakesHelper
end

app/views/admin/makes/_make.erb
<div class = "blockMake">
   <div><%= link_to image_tag(make.avatar.url, width: 200,height: 150),admin_make_path(make) if make.avatar? %> </div>
  <div><%= link_to make.name, admin_make_path(make) %>
    <a style="margin-left : 100px"></a>
    <%= link_to image_tag("icon/glyphicons_150_edit.png"), edit_admin_make_path(make) %></td>
    <%= link_to image_tag("icon/glyphicons_207_remove_2.png"), admin_make_path(make), method: :delete,
                data: { confirm: "You sure?" } %>
  </div>

</div>

app/views/admin/makes/edit.erb
<% content_for :second_title do%>
    Edit Make <%= @make.name %>
<%end%>
<%= render 'shared/navigate',object: @make %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for([:admin,@make]) do |f| %>
        <%= render "shared/error_make_messages" %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <label>Picture</label>
        <%= image_tag(@make.avatar.url, width: 95, height: 95) if @make.avatar? %>
        <%= f.file_field :avatar %>
        <%= f.hidden_field :avatar_cache %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

<script>
    $(function(){

        $(".edit_member_link").addClass('active');
    })
</script>

app/views/admin/makes/index.erb
<div class="right_add">
<%= link_to image_tag("icon/glyphicons_432_plus.png")+" add make", new_admin_make_url, class: "btn" %>
</div>
  <div id = "collection-Make">
    <%= render @makes%>
</div>

app/views/admin/makes/new.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for([:admin, @make]) do |f| %>
        <%= render "shared/error_make_messages" %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <label>Picture</label>
        <%= f.file_field :avatar %>
        <%= f.hidden_field :avatar_cache %>

        <br>
        <%= f.submit "Create makes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/makes/show.erb
<% content_for :second_title do%>
    Show Make <%= @make.name %>
<%end%>
<%= render 'shared/navigate',object: @make %>
<div class = "picture">
  <%= image_tag(@make.avatar_url, width: 400,height: 400) if @make.avatar? %>
</div>
<dl>
  <dt class="label name_field string_type">Name</dt>
  <dd>
    <pre class="prettyprint"><%= @make.name %></pre>
  </dd>
  <dt class="label name_field string_type">Models</dt>
  <dd>
    <pre class="prettyprint">
      <% @make.models.each do |model|%>
        <%= link_to model.model_name, admin_model_path(model)%>//поправить
      <% end %>
    </pre>
  </dd>

</dl>

<script>
    $(function(){
        $(".show_member_link").addClass('active');
    })
</script>