config/routes.rb
Simplesite::Application.routes.draw do
  resources :users, only: [:new, :create, :destroy]

  namespace "admin" do
    get '',to: 'cars#index'
    resources :cars do
      get 'delete_asset' => "cars#delete_asset"
    end
    post 'update_list', to: 'cars#update_list'
    get 'filter', to: 'cars#filter'
    get 'search_by_price', to: 'cars#search_by_price'

    resources :models
    resources :makes
  end

  namespace "front" do
    resources :makes, only: [:index,:show]do
      resources :models, only: [:show,:index]do
        resources :cars, only: [:show,:index] do
        end
      end
    end
  end
  root to: 'index#home'

  resources :sessions, only: [:new, :create, :destroy]

  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy', via: :delete

  get '/signup',  to: 'users#new'

 

  

end

app/models/car.rb
class Car < ActiveRecord::Base

  belongs_to :model
  belongs_to :make
  attr_accessible :displacement,:attached_assets_attributes,:fuel_type,:year,:model_id,:price,:features,:make_id,:avatar
  validates_presence_of :model_id, :price, :fuel_type, :displacement, :features, :make_id, :year
  validates_numericality_of :price, only_integer: true, greater_than: 0, allow_blank: true

  has_many :attached_assets, :as => :attachable
  accepts_nested_attributes_for :attached_assets, :allow_destroy => true

  default_scope order: 'cars.created_at DESC'


  def self.select_car(price_min,price_max)
    if  price_min||price_max
      Car.where("price > ?",price_min.to_i).where("price < ?",price_max)
    else
      Car.all
    end
  end

  def avatar_url
    urls = []
    self.attached_assets.each do |a|
       urls.push(a.asset.url(:normal))
    end
    urls
  end

end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::AdminController

  before_filter   :have_a_car, only: [:edit,:show,:update,:destroy]
  respond_to :js, :json, :html

  def index
    @cars = Car.includes(:model).includes(:make).all
    nil_cookies
    select_make_nil
  end

  def new
    @car = Car.new
  end



  def create
    @car = Car.new(params[:car])
      if @car.save
        flash[:success] = "Create car success"
        redirect_to admin_cars_path
      else
        render 'new'
      end
  end

  def show
  end

  def edit
  end

  def update
     if @car.update_attributes(params[:car])
        redirect_to admin_car_path(@car)
     else
      render 'edit'
    end
  end

  def destroy
    @car.destroy
    flash[:info] = "Car destroyed."
    redirect_to admin_cars_path
  end



  def update_list
    unless params[:make_id].blank?
      make = Make.find(params[:make_id])
      @models = make.models.map{|a| [a.model_name, a.id] }
    else
      @models = []
    end

  end


  def filter
     @car = Car.select_car(cookies[:price_min],cookies[:price_max])

    unless params[:make_id].blank?
      @car = @car.where("make_id = ?",params[:make_id])
      cookies[:select_make] = params[:make_id]
    else
      select_make_nil
    end
     respond_with @car
  end


  def search_by_price
    cookies[:price_min] = params[:price_min]
    cookies[:price_max] = params[:price_max]

    @car = Car.select_car(cookies[:price_min],cookies[:price_max])

    temp_storing = cookies[:select_make]
    unless temp_storing.blank?
      @car = @car.where("make_id = ?",temp_storing)
    end
    respond_with @car
  end

  def delete_asset
    ad = Car.find(params[:car_id])
    asset = ad.attached_assets.find(params[:id])
    asset.asset.clear
    asset.destroy
    ad.save
    redirect_to :back
  end
  private


   def have_a_car
    unless @car = Car.where(id: params[:id]).first
     not_found
    end
   end
end

app/controllers/front/cars_controller.rb
class Front::CarsController < Front::FrontController
  before_filter :have_a_cars
  def index
    render json: @cars.to_json(:methods => [:avatar_url])
  end
  def show
     render json: @cars.find(params[:id]).to_json(:methods => [:avatar_url])
  end
  def have_a_cars
   @cars = Make.friendly.find(params[:make_id]).models.friendly.find(params[:model_id]).cars
  end
end

app/helpers/admin/cars_helper.rb
module Admin::CarsHelper
  def nil_cookies
    cookies[:price_min] = nil
    cookies[:price_max] = nil
  end
  def select_make_nil
    cookies[:select_make] = nil
    cookies[:select_model] = nil
  end
end

app/views/admin/cars/_car.erb
<tr>
    <td><%= link_to image_tag(car.attached_assets.first.asset.url(:mini), width: 60,height: 60),admin_car_path(car) unless car.attached_assets.first.nil?%></td>
    <td><%= link_to car.make.name, admin_make_path(car.make) %></td>
    <td><%= link_to car.model.model_name, admin_model_path(car.model) %> </td>
    <td><%= car.price %> $</td>
    <td><%= car.features %></td>
    <td><%= link_to image_tag("icon/glyphicons_039_notes.png"), admin_car_path(car) %>
    <%= link_to image_tag("icon/glyphicons_150_edit.png"), edit_admin_car_path(car) %>
    <%= link_to image_tag("icon/glyphicons_207_remove_2.png"), admin_car_path(car), method: :delete,
                    data: { confirm: "You sure?" } %></td>
</tr>

app/views/admin/cars/edit.erb
 <% content_for :second_title do%>
      Edit Car <%= @car.features %>
  <%end%>
<%= render 'shared/navigate', object: @car %>
<div class="row">
  <div class="span6 offset3">
    <%= form_for ([:admin,@car]),:html => {:multipart => true} do |f| %>
        <%= render 'shared/error_car_messages' %>

        <%= f.label :fuel_type %>
        <%= f.text_field :fuel_type %>

        <%= f.label :displacement %>
        <%= f.text_field :displacement %>

        <%= f.label :year %>
        <%= f.text_field :year %>

        <%= f.label :make_id %>
        <%= collection_select(:car, :make_id,  Make.all,  :id, :name, {:prompt   => "Select a Make"}, {:id => 'make_select'}) %>

        <%= f.label :model_id, id: :label_car_model_id%>
        <%= collection_select(:car, :model_id,  @car.make.models,  :id, :model_name, {:prompt   => "Select a Model"}) %>


        <%= f.label :price %>
        <%= f.text_field :price %>

        <%= f.label :features %>
        <%= f.text_field :features %>

        <%= f.label :pictures %>
        <% @car.attached_assets.each do |a| %>
            <%= image_tag(a.asset.url(:mini)) %>
            <p>
            <%= link_to "Удалить", admin_car_delete_asset_path(car_id: a.attachable_id, id: a.id) %>
        <% end %>
        <p>
        <%= file_field_tag('car_attached_assets_asset', multiple: true, name: "car[attached_assets_attributes][][asset]") %>
        <p>
        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

<script>
    $(function(){
        $(".edit_member_link").addClass('active');
    })
</script>

app/views/admin/cars/filter.js.erb
$("#car_table").html("<%= escape_javascript(render(@car)) %>")

app/views/admin/cars/index.erb
<% content_for(:title, 'Admin Cars')%>

<h3>List cars</h3>
<div class="left_search">
  <div class = "search">
    <%= form_tag("/search_by_price", method:  "get", remote: true) do %>
        from <%= text_field_tag :price_min%>
        to <%= text_field_tag :price_max%>
        <%= submit_tag "search", class: "btn correct"%>
    <% end %>
  </div>

  <div class="filter">
    <%= collection_select(nil, :make_id,  Make.all,  :id, :name, {:prompt   => "Select a Make"}, {:id => 'make_selects'}) %>
  </div>

</div>
<div class="right_add"><%= link_to image_tag("icon/glyphicons_432_plus.png")+" add car", new_admin_car_url, class: "btn" %></div>

<table class="table">
  <thead>
  <tr>
    <th></th>
    <th>Make</th>
    <th>Model</th>
    <th>price</th>
    <th>features</th>
    <th></th>
  </tr>
  </thead>
  <tbody id="car_table">
  <%= render @cars %>
  </tbody>
</table>

app/views/admin/cars/new.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for ([:admin,@car]),:html => {:multipart => true} do |f| %>
        <%= render 'shared/error_car_messages' %>

        <%= f.label :fuel_type %>
        <%= f.text_field :fuel_type %>

        <%= f.label :displacement %>
        <%= f.text_field :displacement %>

        <%= f.label :year %>
        <%= f.text_field :year %>

        <%= f.label :make_id %>
         <%= collection_select(:car, :make_id,  Make.all,  :id, :name, {:prompt   => "Select a Make"}, {:id => 'make_select'}) %>

        <%= f.label :model_id, id: :label_car_model_id%>
        <%= collection_select(:car, :model_id,  [],  :id, :model_name, {:prompt   => "Select a Model"}) %>

        <%= f.label :price %>
        <%= f.text_field :price %>

        <%= f.label :features %>
        <%= f.text_field :features %>

        <%= file_field_tag('car_attached_assets_asset', multiple: true, name: "car[attached_assets_attributes][][asset]") %>

        <%= f.submit "Create car", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<script>
    $('#car_model_id').hide();
    $('#label_car_model_id').hide();
</script>

app/views/admin/cars/search_by_price.js.erb
$("#car_table").html("<%= escape_javascript(render(@car)) %>")

app/views/admin/cars/show.erb
  <% content_for :second_title do%>
      Details for Car <%= @car.features %>
  <%end%>

<%= render 'shared/navigate', object: @car %>
    <h4>
      Basic info
    </h4>

<div class = "picture">

  <div class="slider">
    <% i = 0 %>
    <% @car.attached_assets.each do |a| %>
        <input type="radio" name="slide_switch" id="id<%= i %>" <%=  "checked = checked" if i==0 %>/>
        <label for="id<%= i %>">
          <%= image_tag(a.asset.url(:normal),width: 100) %>
        </label>
        <%= image_tag(a.asset.url(:normal)) %>
        <% i=i+1 %>
    <% end %>
  </div>
</div>
<dl>
  <dt class="label name_field string_type">Make</dt>
  <dd>
    <pre class="prettyprint"><%=link_to @car.make.name, admin_make_path(@car.make)%></pre>
  </dd>

  <dt class="label name_field string_type">Model</dt>
  <dd>
    <pre class="prettyprint"><%=link_to @car.model.model_name, admin_model_path(@car.model)%></pre>
  </dd>

  <dt class="label name_field string_type">fuel type</dt>
  <dd>
    <pre class="prettyprint"><%=@car.fuel_type %></pre>
  </dd>

  <dt class="label name_field string_type">displacement</dt>
  <dd>
    <pre class="prettyprint"><%=@car.displacement %></pre>
  </dd>

  <dt class="label name_field string_type">year</dt>
  <dd>
    <pre class="prettyprint"><%=@car.year %></pre>
  </dd>

  <dt class="label name_field string_type">features</dt>
  <dd>
    <pre class="prettyprint"><%=@car.features %></pre>
  </dd>

  <dt class="label name_field string_type">price</dt>
  <dd>
    <pre class="prettyprint text-success"><%=@car.price %> $</pre>
  </dd>
</dl>
<script>
    $(function(){
        $(".show_member_link").addClass('active');
    })
</script>

app/views/admin/cars/update_list.js.erb
if(<%= @models.any? %>){
	$('#car_model_id').html("<%= escape_javascript(options_for_select(@models)) %>");
    $('#car_model_id').show('slow');
    $('#label_car_model_id').show('slow');
}
else{
	$('#car_model_id').html("<%= escape_javascript(options_for_select([nil,nil])) %>");
    $('#car_model_id').hide('slow');
    $('#label_car_model_id').hide('slow');

}