config/routes.rb
Simplesite::Application.routes.draw do
  resources :users, only: [:new, :create, :destroy]

  namespace "admin" do
    get '',to: 'cars#index'
    resources :cars do
      get 'delete_asset' => "cars#delete_asset"
    end
    post 'update_list', to: 'cars#update_list'
    get 'filter', to: 'cars#filter'
    get 'search_by_price', to: 'cars#search_by_price'

    resources :models
    resources :makes
  end

  namespace "front" do
    resources :makes, only: [:index,:show]do
      resources :models, only: [:show,:index]do
        resources :cars, only: [:show,:index] do
        end
      end
    end
  end
  root to: 'index#home'

  resources :sessions, only: [:new, :create, :destroy]

  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy', via: :delete

  get '/signup',  to: 'users#new'

 

  

end

app/models/attached_asset.rb
class AttachedAsset < ActiveRecord::Base
  belongs_to :car, :polymorphic => true
  has_attached_file :asset, :styles => { :mini => "64x32#", :normal => "640x320#"}
  attr_accessible :asset, :asset_file_name
end

app/models/car.rb
class Car < ActiveRecord::Base

  belongs_to :model
  belongs_to :make
  attr_accessible :displacement,:attached_assets_attributes,:fuel_type,:year,:model_id,:price,:features,:make_id,:avatar
  validates_presence_of :model_id, :price, :fuel_type, :displacement, :features, :make_id, :year
  validates_numericality_of :price, only_integer: true, greater_than: 0, allow_blank: true

  has_many :attached_assets, :as => :attachable
  accepts_nested_attributes_for :attached_assets, :allow_destroy => true

  default_scope order: 'cars.created_at DESC'


  def self.select_car(price_min,price_max)
    if  price_min||price_max
      Car.where("price > ?",price_min.to_i).where("price < ?",price_max)
    else
      Car.all
    end
  end

  def avatar_url
    urls = []
    self.attached_assets.each do |a|
       urls.push(a.asset.url(:normal))
    end
    urls
  end

end

app/models/make.rb
class Make < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  attr_accessible :name,:avatar

  has_many :models, dependent: :destroy
  has_many :cars, dependent: :destroy

  validates :name, presence: true
  validates_uniqueness_of  :name

  default_scope order: 'makes.created_at DESC'

  mount_uploader :avatar, AvatarUploader
end

app/models/model.rb
class Model < ActiveRecord::Base

  extend FriendlyId
  friendly_id :model_name, use: :slugged
  attr_accessible :model_name,:make_id,:avatar

  has_many :cars, dependent: :destroy
  belongs_to :make

  validates_presence_of  :model_name, :make_id
  validates_uniqueness_of  :model_name

  mount_uploader :avatar, AvatarUploader

  default_scope order: 'models.created_at DESC'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :create_remember_token
  attr_accessible :name,:email,:password
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  before_save { |user| user.email = email.downcase }

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/admin/models_controller.rb
class Admin::ModelsController < Admin::AdminController

  before_filter   :have_a_model, only: [:update,:destroy,:show,:edit]

  def index
    @models = Model.includes(:make).all
  end

  def new
    @model = Model.new

  end

  def create
    @model = Model.new(params[:model])
    if @model.save
      flash[:success] = "Create model success"
      redirect_to admin_models_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @model.update_attributes(params[:model])
       @model.slug = nil
       @model.save 
       redirect_to admin_model_path(@model)
    else
      render 'edit'
    end
  end



  def destroy
    @model.destroy
    flash[:info] = "Model destroyed."
    redirect_to admin_models_path
  end

  private
  def  have_a_model
    unless @model = Model.friendly.find(params[:id])
      not_found
    end
  end

end

app/controllers/front/models_controller.rb
class Front::ModelsController < Front::FrontController
  before_filter :have_a_model
  def index
    render json: @models
  end
  def show
    render json: @models.friendly.find(params[:id])
  end

  def have_a_model
    @models = Make.friendly.find(params[:make_id]).models
  end
end

app/helpers/admin/models_helper.rb
module Admin::ModelsHelper
end

app/views/admin/models/_model.erb
<tr>
  <td ><%= link_to image_tag(model.avatar_url, width: 60,height: 60),model if model.avatar? %></td>
  <td><%=   model.model_name %></td>
  <td><%=  link_to model.make.name, admin_make_path(model.make) %></td>
  <td class = "last links"><%= link_to image_tag("icon/glyphicons_039_notes.png"), admin_model_path(model) %>
  <%= link_to image_tag("icon/glyphicons_150_edit.png"), edit_admin_model_path(model) %>
  <%= link_to image_tag("icon/glyphicons_207_remove_2.png"), admin_model_path(model), method: :delete,
                  data: { confirm: "You sure?" } %></td>
</tr>

app/views/admin/models/edit.erb
<% content_for :second_title do%>
      Edit Model <%= @model.model_name %>
<%end%>

<%= render 'shared/navigate',object: @model %>

<div class="row">
  <div class="span6 offset3">
    <%= form_for([:admin,@model]) do |f| %>

        <%= f.label :make_id %>
        <%= collection_select(:model, :make_id, Make.all, :id, :name) %>

        <%= f.label :model_name %>
        <%= f.text_field :model_name %>

        <label>Picture</label>
        <%= image_tag(@model.avatar.url, width: 95, height: 95) if @model.avatar? %>
        <%= f.file_field :avatar %>
        <%= f.hidden_field :avatar_cache %>
        <br>
        <div class= "form-actions">
        <%= f.submit "Save",name: "_save" ,class: "btn btn-primary" %>
        </div>
    <% end %>
  </div>
</div>

<script>
    $(function(){

        $(".edit_member_link").addClass('active');
    })
</script>

app/views/admin/models/index.erb
<div class="right_add">
  <%= link_to image_tag("icon/glyphicons_432_plus.png")+"Add model",new_admin_model_path,class: :btn%>
</div>
<br>
<table class="table">
  <thead>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Make</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
     <%= render @models %>
  </tbody>
</table>

app/views/admin/models/new.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for([:admin,@model]) do |f| %>

        <%= f.label :model_name %>
        <%= f.text_field :model_name %>


        <%= f.label :make_id %>
        <%= collection_select(:model, :make_id, Make.all, :id, :name) %>

        <label>Picture</label>
        <%= f.file_field :avatar %>
        <%= f.hidden_field :avatar_cache %>
        <br>
        <%= f.submit "Create model", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/admin/models/show.erb
<% content_for :second_title do%>
      Details for Model <%= @model.model_name %>
<%end%>
<%= render 'shared/navigate', object: @model %>
<h4>
  Basic info
</h4>
<div class = "picture">
  <%= image_tag(@model.avatar_url, width: 400,height: 400) if @model.avatar? %>
</div>
<dl>
  <dt class="label name_field string_type">Name</dt>
  <dd>
    <pre class="prettyprint"><%= @model.model_name %></pre>
  </dd>
  <dt class="label name_field string_type">Make</dt>
  <dd>
    <pre class="prettyprint"><%= link_to @model.make.name, admin_make_path(@model.make) %></pre>
  </dd>
  <dt class="label name_field string_type">Cars</dt>
  <dd>
    <pre class="prettyprint">
      <% @model.cars.each do |car|%>
        <%= link_to car.features, admin_car_path(car)%>//поправить
      <% end %>
    </pre>
  </dd>

</dl>
<script>
    $(function(){

        $(".show_member_link").addClass('active');
    })
</script>