config/routes.rb
Simplesite::Application.routes.draw do
  resources :users, only: [:new, :create, :destroy]

  namespace "admin" do
    get '',to: 'cars#index'
    resources :cars do
      get 'delete_asset' => "cars#delete_asset"
    end
    post 'update_list', to: 'cars#update_list'
    get 'filter', to: 'cars#filter'
    get 'search_by_price', to: 'cars#search_by_price'

    resources :models
    resources :makes
  end

  namespace "front" do
    resources :makes, only: [:index,:show]do
      resources :models, only: [:show,:index]do
        resources :cars, only: [:show,:index] do
        end
      end
    end
  end
  root to: 'index#home'

  resources :sessions, only: [:new, :create, :destroy]

  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy', via: :delete

  get '/signup',  to: 'users#new'

 

  

end

app/models/attached_asset.rb
class AttachedAsset < ActiveRecord::Base
  belongs_to :car, :polymorphic => true
  has_attached_file :asset, :styles => { :mini => "64x32#", :normal => "640x320#"}
  attr_accessible :asset, :asset_file_name
end

app/models/car.rb
class Car < ActiveRecord::Base

  belongs_to :model
  belongs_to :make
  attr_accessible :displacement,:attached_assets_attributes,:fuel_type,:year,:model_id,:price,:features,:make_id,:avatar
  validates_presence_of :model_id, :price, :fuel_type, :displacement, :features, :make_id, :year
  validates_numericality_of :price, only_integer: true, greater_than: 0, allow_blank: true

  has_many :attached_assets, :as => :attachable
  accepts_nested_attributes_for :attached_assets, :allow_destroy => true

  default_scope order: 'cars.created_at DESC'


  def self.select_car(price_min,price_max)
    if  price_min||price_max
      Car.where("price > ?",price_min.to_i).where("price < ?",price_max)
    else
      Car.all
    end
  end

  def avatar_url
    urls = []
    self.attached_assets.each do |a|
       urls.push(a.asset.url(:normal))
    end
    urls
  end

end

app/models/make.rb
class Make < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  attr_accessible :name,:avatar

  has_many :models, dependent: :destroy
  has_many :cars, dependent: :destroy

  validates :name, presence: true
  validates_uniqueness_of  :name

  default_scope order: 'makes.created_at DESC'

  mount_uploader :avatar, AvatarUploader
end

app/models/model.rb
class Model < ActiveRecord::Base

  extend FriendlyId
  friendly_id :model_name, use: :slugged
  attr_accessible :model_name,:make_id,:avatar

  has_many :cars, dependent: :destroy
  belongs_to :make

  validates_presence_of  :model_name, :make_id
  validates_uniqueness_of  :model_name

  mount_uploader :avatar, AvatarUploader

  default_scope order: 'models.created_at DESC'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :create_remember_token
  attr_accessible :name,:email,:password
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  before_save { |user| user.email = email.downcase }

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  include SessionsHelper
  include Admin::CarsHelper

  before_filter   :signed_in

  def give_last_page
    session[:last_page] = request.env['HTTP_REFERER']
  end

  def not_found
    render :file => 'public/404.html', :status => :not_found, :layout => false
  end

  def signed_in
    if !signed_in?
      flash[:info] = 'You must be identified'
      redirect_to new_session_path
    end
  end
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::AdminController

  before_filter   :have_a_car, only: [:edit,:show,:update,:destroy]
  respond_to :js, :json, :html

  def index
    @cars = Car.includes(:model).includes(:make).all
    nil_cookies
    select_make_nil
  end

  def new
    @car = Car.new
  end



  def create
    @car = Car.new(params[:car])
      if @car.save
        flash[:success] = "Create car success"
        redirect_to admin_cars_path
      else
        render 'new'
      end
  end

  def show
  end

  def edit
  end

  def update
     if @car.update_attributes(params[:car])
        redirect_to admin_car_path(@car)
     else
      render 'edit'
    end
  end

  def destroy
    @car.destroy
    flash[:info] = "Car destroyed."
    redirect_to admin_cars_path
  end



  def update_list
    unless params[:make_id].blank?
      make = Make.find(params[:make_id])
      @models = make.models.map{|a| [a.model_name, a.id] }
    else
      @models = []
    end

  end


  def filter
     @car = Car.select_car(cookies[:price_min],cookies[:price_max])

    unless params[:make_id].blank?
      @car = @car.where("make_id = ?",params[:make_id])
      cookies[:select_make] = params[:make_id]
    else
      select_make_nil
    end
     respond_with @car
  end


  def search_by_price
    cookies[:price_min] = params[:price_min]
    cookies[:price_max] = params[:price_max]

    @car = Car.select_car(cookies[:price_min],cookies[:price_max])

    temp_storing = cookies[:select_make]
    unless temp_storing.blank?
      @car = @car.where("make_id = ?",temp_storing)
    end
    respond_with @car
  end

  def delete_asset
    ad = Car.find(params[:car_id])
    asset = ad.attached_assets.find(params[:id])
    asset.asset.clear
    asset.destroy
    ad.save
    redirect_to :back
  end
  private


   def have_a_car
    unless @car = Car.where(id: params[:id]).first
     not_found
    end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/front/cars_controller.rb
class Front::CarsController < Front::FrontController
  before_filter :have_a_cars
  def index
    render json: @cars.to_json(:methods => [:avatar_url])
  end
  def show
     render json: @cars.find(params[:id]).to_json(:methods => [:avatar_url])
  end
  def have_a_cars
   @cars = Make.friendly.find(params[:make_id]).models.friendly.find(params[:model_id]).cars
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :signed_in
  def index
    not_found
  end
  def new
    if signed_in?
      flash[:info] = 'You are logined' # Not quite right!
      redirect_to :back
    end
  end

  def create
    user = User.find_by_email(session_param[:email].downcase)
    if user && user.password ==  session_param[:password]
      sign_in user
      redirect_to cars_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  private
  def session_param
    params.require(:session).permit(:email,:password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :signed_in
  def new
    if signed_in?
      flash[:info] = 'You are logined' # Not quite right!
      redirect_to :back
    else
      @user = User.new
    end
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      sign_in @user
        redirect_to cars_path
    else
      render 'new'
    end
  end

end

app/helpers/admin/cars_helper.rb
module Admin::CarsHelper
  def nil_cookies
    cookies[:price_min] = nil
    cookies[:price_max] = nil
  end
  def select_make_nil
    cookies[:select_make] = nil
    cookies[:select_model] = nil
  end
end

app/helpers/admin/makes_helper.rb
module Admin::MakesHelper
end

app/helpers/admin/models_helper.rb
module Admin::ModelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    "Site by Andrey |  #{page_title}"
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/javascripts_helper.rb
module JavascriptsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def signed_in?
    !current_user.nil?
  end



  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end



end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/index/home.html.erb
  <div id = "nav_list_makes">
   <ul id = "nav" class="nav nav-tabs">
   </ul>
  </div>
  <div class="clear_both"></div>

  <div id = "breadcrumb">
    <ul>
      <li><a href="#">home</a></li>
      <li id = 'make' class = 'list'></li>
      <li id = 'model' class = 'list'></li>
      <li id = 'car' class = 'list'></li>
    </ul>
  </div>
  <div class="clear_both"></div>

          <div id = "body_back_end">
            <div id = 'nav_list_models'>
              <ul id ='list_models'>
              </ul>
            </div>
            <div id="content_body"></div>
          </div>
          <div id="error"></div>


  <div class="clear_both"></div>


  <script id="entry-template" type="text/x-handlebars-template">

    <div class="slider">
      {{#each avatar_url}}
      <input type="radio" name="slide_switch" id="id{{@index}}"checked="checked"/>
      <label for="id{{@index}}">
        <img src="{{this}}" width="100"/>
      </label>
      <img src="{{this}}"/>
      {{/each}}
    </div>


  </script>

  <% if !signed_in? %>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">#</a>
  </small>
  <nav>
    <ul>
      <li></li>
      <li></li>
     </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <% if signed_in? %>
          <ul class="pull-left myconfig">
            <li> <%= link_to "Cars", admin_cars_path %> <span><%= Car.count %></span></li>
            <li>  <%= link_to "Models", admin_models_path %>  <span><%= Model.count %></span></li>
            <li>  <%= link_to "Makes", admin_makes_path %>  <span><%= Make.count %></span></li>
         </ul>

      <% end %>

      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield :title) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>

  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

  </head>
<body>
<%= render 'layouts/header' %>

    <div class="container">

      <div class="page-header">
        <h3><%= yield :second_title %></h3>
      </div>

          <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>
          <%= debug(params) if Rails.env.development? %>
   </div>
</body>
</html>

app/views/shared/_error_car_messages.erb
<% if @car.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@car.errors.count, "error") %>.
      </div>
      <ul>
        <% @car.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_error_make_messages.erb
<% if @make.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@make.errors.count, "error") %>.
      </div>
      <ul>
        <% @make.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_error_model_messages.erb
<% if @car.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@car.errors.count, "error") %>.
      </div>
      <ul>
        <% @car.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_navigate.erb
<ul class="nav nav-tabs">

  <li title="" rel="" class="icon show_member_link">
    <%= link_to "Show", "/admin/#{object.class.to_s.downcase}s/#{object.id}" %>

  </li>

  <li title="" rel="" class="icon edit_member_link ">
    <%= link_to "Edit", "/admin/#{object.class.to_s.downcase}s/#{object.id}/edit"%>
  </li>

  <li title="" rel="" class="icon delete_member_link ">
    
  </li>
</ul>